name: Pipeline CICD projet Master Dev

on:
  push:
    branches:
      - develop

env:
  IMAGE_NAME: tp_devops_cicd_dev
  REPO_URL: ghcr.io
  REPO_USER_LOWER: lordwe4pons

jobs:
  test_backend_db:
    name: Test backend & db
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Npm install
        run: cd backend && npm install

      - name: Lancer les tests backend & db
        run: cd backend && npm test

  test_frontend:
    name: Test frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lancer les tests frontend
        run: cd frontend && ls -lah

  build:
    needs: [test_backend_db, test_frontend]
    name: Build push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name : GHCR Log in
        uses: docker/login-action@v2
        with:
          registry: ${{env.REPO_URL}}
          username: ${{env.REPO_USER_LOWER}}
          password: ${{secrets.CICDTOKEN}}

      - name: Build and Push Backend
        run: |
          docker build -t ${{env.REPO_URL}}/${{env.REPO_USER_LOWER}}/tp_devops_backend_dev:develop ./backend
          docker push ${{env.REPO_URL}}/${{env.REPO_USER_LOWER}}/tp_devops_backend_dev:develop

      - name: Build and Push Frontend
        run: |
          docker build -t ${{env.REPO_URL}}/${{env.REPO_USER_LOWER}}/tp_devops_frontend_dev:develop ./frontend
          docker push ${{env.REPO_URL}}/${{env.REPO_USER_LOWER}}/tp_devops_frontend_dev:develop

  deploy_dev:
    needs: build
    name: Deploy Dev
    runs-on: ubuntu-latest
    steps:
      - name: connexion SSH (Dev)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USER_DEV }}
          key: ${{ secrets.KEY_DEV }}
          script: |
            echo ${{secrets.CICDTOKEN}} | docker login ghcr.io -u ${{env.REPO_USER_LOWER}} --password-stdin
            
            docker network create app-network-dev || true
            
            docker stop tp_devops_frontend_dev tp_devops_backend_dev tp_devops_db_dev || true
            docker rm tp_devops_frontend_dev tp_devops_backend_dev tp_devops_db_dev || true
            
            docker pull ${{env.REPO_URL}}/${{env.REPO_USER_LOWER}}/tp_devops_db_dev:develop
            docker pull ${{env.REPO_URL}}/${{env.REPO_USER_LOWER}}/tp_devops_backend_dev:develop
            docker pull ${{env.REPO_URL}}/${{env.REPO_USER_LOWER}}/tp_devops_frontend_dev:develop
            
            docker run -d --name tp_devops_db_dev --network app-network-dev \
              -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=userdb \
              ${{env.REPO_URL}}/${{env.REPO_USER_LOWER}}/tp_devops_db_dev:develop
            
            docker run -d --name tp_devops_backend_dev --network app-network-dev -p 3000:3000 \
              -e DB_HOST=tp_devops_db_dev -e DB_USER=postgres -e DB_PASSWORD=postgres -e DB_NAME=userdb \
              ${{env.REPO_URL}}/${{env.REPO_USER_LOWER}}/tp_devops_backend_dev:develop
            
            docker run -d --name tp_devops_frontend_dev --network app-network-dev -p 8080:80 \
              ${{env.REPO_URL}}/${{env.REPO_USER_LOWER}}/tp_devops_frontend_dev:develop
